version: '3'

networks:
  server-network:
    driver: bridge

services:
  session:
    image: redis:6.2-alpine
    container_name: db-session
    restart: always
    networks:
      - server-network
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - '${RMQ_PORT}:5672'
      - 15672:15672
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: '${RMQ_USER}'
      RABBITMQ_DEFAULT_PASS: '${RMQ_PASS}'
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    networks:
      - server-network

  auth:
    restart: always
    container_name: auth
    networks:
      - server-network
    image: registry.warehousai.com/warehouse-backend/siyoga/warehouse-auth:latest
    command: ./auth
    depends_on:
      - session
      - rabbitmq
    env_file: .env
    environment:
      DB_NAME: '${AUTH_DB_NAME}'
      DB_PASS: '${AUTH_DB_PASS}'
      DB_USER: '${AUTH_DB_USER}'
      DB_PORT: '${AUTH_DB_PORT}'
    ports:
      - 8040:8040
      - 8041:8041

  user:
    restart: always
    container_name: user
    networks:
      - server-network
    image: registry.warehousai.com/warehouse-backend/siyoga/warehouse-user:latest
    command: ./user
    depends_on:
      - rabbitmq
    env_file: .env
    environment:
      DB_NAME: '${USERS_DB_NAME}'
      DB_PASS: '${USERS_DB_PASS}'
      DB_USER: '${USERS_DB_USER}'
      DB_PORT: '${USERS_DB_PORT}'
    ports:
      - 8000:8000
      - 8001:8001

  mail:
    restart: always
    container_name: mail
    networks:
      - server-network
    env_file: .env
    image: registry.warehousai.com/warehouse-backend/siyoga/warehouse-mail:latest
    command: ./mail
    depends_on:
      - user
      - auth
      - rabbitmq

  ai:
    restart: always
    container_name: ai
    networks:
      - server-network
    image: registry.warehousai.com/warehouse-backend/siyoga/warehouse-ai:latest
    command: ./ai
    env_file: .env
    ports:
      - 8020:8020
      - 8021:8021
