version: '3'

networks:
  svc-network:
    driver: bridge

services:
  proxy:
    image: nginx:1.24-alpine
    container_name: proxy_server
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - user
      - ai
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - svc-network

  auth:
    restart: always
    container_name: auth-service
    networks:
      - svc-network
    build:
      context: .
      dockerfile: dockerfiles/auth.Dockerfile
    command: ./auth
    depends_on:
      - user
    env_file: .env
    expose:
      - '8001'
    ports:
      - 8010:8010

  user:
    restart: always
    container_name: user-service
    networks:
      - svc-network
    build:
      context: .
      dockerfile: dockerfiles/user.Dockerfile
    command: ./wait-4-postgres.sh data_db ./user
    env_file: .env
    ports:
      - 8000:8000
      - 8001:8001

  ai:
    restart: always
    container_name: ai-service
    networks:
      - svc-network
    build:
      context: .
      dockerfile: dockerfiles/ai.Dockerfile
    command: ./wait-4-postgres.sh data_db ./ai
    env_file: .env
    ports:
      - 8020:8020
